"""
Stage 2 plotting script: thesis Figures 13 and 14.

This script reproduces Figures 13 and 14 of the thesis for the stationary
inverse problem. It reads history files generated by NS_xy_stage2.py and
plots the evolution of the inferred inlet pressure p_in.

The script does not train a model. The required history files must first be
generated by running the corresponding Stage 2 experiments.

Paths are resolved automatically relative to the repository root.
"""

from pathlib import Path

import numpy as np
import torch
import matplotlib.pyplot as plt


# =========================
# Configuration
# =========================

SHOW_PLOTS = False
OVERWRITE_EXISTING_OUTPUTS = False

REPO_ROOT = Path(__file__).resolve().parents[1]

HISTORY_DIR = REPO_ROOT / "stage2_stationary_inverse" / "histories"
EXTERNAL_FIGURES_DIR = (
    REPO_ROOT
    / "stage2_stationary_inverse"
    / "external_figures"
)

COMPARISON_RUNS = [
    {
        "label": "5 points",
        "filename": "stage2_pinit8_points5.pt",
        "p_in_initial": 8.0,
        "data_points": 5,
        "adam_epochs": 5000,
    },
    {
        "label": "4 points",
        "filename": "stage2_pinit8_points4.pt",
        "p_in_initial": 8.0,
        "data_points": 4,
        "adam_epochs": 5000,
    },
    {
        "label": "3 points",
        "filename": "stage2_pinit8_points3.pt",
        "p_in_initial": 8.0,
        "data_points": 3,
        "adam_epochs": 5000,
    },
    {
        "label": "2 points",
        "filename": "stage2_pinit8_points2.pt",
        "p_in_initial": 8.0,
        "data_points": 2,
        "adam_epochs": 5000,
    },
]

EXTREME_RUN = {
    "filename": "stage2_pinit20_points2.pt",
    "p_in_initial": 20.0,
    "data_points": 2,
    "adam_epochs": 10000,
}


# =========================
# Utilities
# =========================

def stop_if_output_exists(path):
    path = Path(path)

    if path.exists() and not OVERWRITE_EXISTING_OUTPUTS:
        raise FileExistsError(
            f"Output file already exists and would be overwritten:\n"
            f"{path}\n\n"
            f"Delete the existing file or set OVERWRITE_EXISTING_OUTPUTS = True."
        )


def load_torch_checkpoint(path):
    try:
        return torch.load(path, map_location="cpu", weights_only=False)
    except TypeError:
        return torch.load(path, map_location="cpu")


def load_history(run_info):
    filename = run_info["filename"]
    path = HISTORY_DIR / filename

    if not path.exists():
        raise FileNotFoundError(
            f"Missing history file:\n"
            f"{path}\n\n"
            f"Generate it first by running NS_xy_stage2.py with:\n"
            f"P_IN_INITIAL = {run_info['p_in_initial']}\n"
            f"DATA_POINTS = {run_info['data_points']}\n"
            f"ADAM_EPOCHS = {run_info['adam_epochs']}\n"
            f"SAVE_HISTORY = True\n"
        )

    ckpt = load_torch_checkpoint(path)

    required_keys = [
        "adam_epochs",
        "epoch_history",
        "p_in_history",
        "p_in_history_lbfgs",
        "p_in_reference",
        "p_in_initial",
        "data_points",
    ]

    missing_keys = [key for key in required_keys if key not in ckpt]

    if missing_keys:
        raise KeyError(
            f"History file '{path}' is missing required keys: {missing_keys}"
        )

    if int(ckpt["data_points"]) != run_info["data_points"]:
        raise ValueError(f"History file '{path}' was generated with a different DATA_POINTS value.")

    if not np.isclose(float(ckpt["p_in_initial"]), run_info["p_in_initial"]):
        raise ValueError(f"History file '{path}' was generated with a different P_IN_INITIAL value.")

    if int(ckpt["adam_epochs"]) != run_info["adam_epochs"]:
        raise ValueError(f"History file '{path}' was generated with a different ADAM_EPOCHS value.")

    return ckpt

def split_adam_lbfgs_curve(ckpt):
    """
    Returns separate Adam and L-BFGS curves.
    The L-BFGS curve starts exactly from the final Adam point.
    """

    adam_x = np.asarray(ckpt["epoch_history"], dtype=float)
    adam_y = np.asarray(ckpt["p_in_history"], dtype=float)

    if adam_x.size == 0 or adam_y.size == 0:
        raise ValueError("History file contains empty Adam history.")

    if adam_x.shape[0] != adam_y.shape[0]:
        raise ValueError(
            "epoch_history and p_in_history must have the same length."
        )

    lbfgs_y_raw = np.asarray(ckpt["p_in_history_lbfgs"], dtype=float)

    transition_step = adam_x[-1]

    if len(lbfgs_y_raw) > 0:
        lbfgs_x = np.concatenate([
            np.array([transition_step]),
            transition_step + np.arange(1, len(lbfgs_y_raw) + 1),
        ])

        lbfgs_y = np.concatenate([
            np.array([adam_y[-1]]),
            lbfgs_y_raw,
        ])

    else:
        lbfgs_x = np.array([])
        lbfgs_y = np.array([])

    return adam_x, adam_y, lbfgs_x, lbfgs_y, transition_step


def save_fig(fig, filename, dpi=300):
    EXTERNAL_FIGURES_DIR.mkdir(
        parents=True,
        exist_ok=True
    )

    path = EXTERNAL_FIGURES_DIR / filename
    stop_if_output_exists(path)

    fig.savefig(
        path,
        dpi=dpi,
        bbox_inches="tight"
    )

    print(f"Saved: {path}")


def show_or_close(fig):
    if SHOW_PLOTS:
        plt.show()
    else:
        plt.close(fig)


# =========================
# Figure 13: comparison of 5, 4, 3, 2 pressure points
# =========================

def plot_pressure_point_comparison():
    fig, ax = plt.subplots(figsize=(10, 6))

    transition_step_for_plot = None
    target_pin = None

    for run_info in COMPARISON_RUNS:
        ckpt = load_history(run_info)

        adam_x, adam_y, lbfgs_x, lbfgs_y, transition_step = split_adam_lbfgs_curve(ckpt)

        if transition_step_for_plot is None:
            transition_step_for_plot = transition_step

        if target_pin is None:
            target_pin = float(ckpt["p_in_reference"])

        if len(lbfgs_y) > 0:
            x_all = np.concatenate([adam_x, lbfgs_x[1:]])
            y_all = np.concatenate([adam_y, lbfgs_y[1:]])
        else:
            x_all = adam_x
            y_all = adam_y

        ax.plot(
            x_all,
            y_all,
            linewidth=2.0,
            label=run_info["label"],
        )

    ax.axhline(
        target_pin,
        color="black",
        linestyle="--",
        linewidth=1.4,
        label=rf"$p_{{in}}={target_pin:.0f}$ Pa",
    )

    if transition_step_for_plot is not None:
        ax.axvline(
            transition_step_for_plot,
            color="black",
            linestyle=":",
            linewidth=1.4,
            alpha=0.8,
            label="Adam → L-BFGS transition",
        )

    ax.set_xlabel("Training step")
    ax.set_ylabel(r"$p_{in}$ (Pa)")
    ax.set_title("Convergence of the inferred inlet pressure")
    ax.grid(True, alpha=0.3)
    ax.legend(loc="best")

    plt.tight_layout()

    save_fig(fig, "pin_comparison_pinit8_points2to5.png")
    show_or_close(fig)


# =========================
# Figure 14: extreme scenario p_in_initial = 20 Pa, 2 points
# =========================

def plot_extreme_initial_pressure_case():
    ckpt = load_history(EXTREME_RUN)

    adam_x, adam_y, lbfgs_x, lbfgs_y, transition_step = split_adam_lbfgs_curve(ckpt)

    target_pin = float(ckpt["p_in_reference"])

    fig, ax = plt.subplots(figsize=(10, 6))

    ax.plot(
        adam_x,
        adam_y,
        linewidth=1.8,
        label=r"$p_{in}$ Adam",
    )

    if len(lbfgs_y) > 0:
        ax.plot(
            lbfgs_x,
            lbfgs_y,
            linewidth=1.8,
            label=r"$p_{in}$ L-BFGS",
        )

    ax.axhline(
        target_pin,
        color="black",
        linestyle="--",
        linewidth=1.4,
        label=rf"$p_{{in}} = {target_pin:.0f}$ Pa",
    )

    ax.axvline(
        transition_step,
        color="black",
        linestyle=":",
        linewidth=1.4,
        alpha=0.8,
        label="Adam → L-BFGS transition",
    )

    ax.set_xlabel("Training step")
    ax.set_ylabel(r"$p_{in}$ (Pa)")
    ax.set_title("Convergence of the inferred inlet pressure")
    ax.grid(True, alpha=0.3)
    ax.legend(loc="best")

    plt.tight_layout()

    save_fig(fig, "pin_extreme_pinit20_points2.png")
    show_or_close(fig)


# =========================
# Main
# =========================

def main():
    plot_pressure_point_comparison()
    plot_extreme_initial_pressure_case()


if __name__ == "__main__":
    main()